### ISSUE TITLE
Verify Domain

### ISSUE THREAD

**Issue by hutson** [conventional-commits/meta#1]
Can we use the [_Verified domains_ feature](https://blog.github.com/changelog/2018-08-07-domain-verification/) under our org _Settings_ to verify the `conventionalcommits.org` domain.

**Comment by bcoe** [comment]
👋 I'm currently hosting the domain, I think I will need to do this; ping me in slack if I drag my feet at all http://devtoolscommunity.herokuapp.com/

**Comment by damianopetrungaro** [comment]
@bcoe any update?

**Comment by hutson** [comment]
Ping @bcoe :smiley:

**Comment by bcoe** [comment]
done 👍
