### ISSUE TITLE
Move parser to this org

### ISSUE THREAD

**Issue by wesleytodd** [conventional-commits/meta#4]
It seems to me that since the spec lives here, so should the parser.  Thoughts?

Having separate issues and history from the monorepo where it lives today would be helpful for me, as I have been struggling to find the right place to start contributing, and don't really care to touch all those project specific configuration packages which live together in the monorepo.

I would be happy to extract just the git history from that directory so we can maintain the references, but it would mean loosing the related issues and any open PRs.  IMO, this is a fine tradeoff for a better future, but it is one downside of doing this.

FWIW, I would also like to look at pulling out the other "foundational" packages like `git-raw-commits` and `git-semver-tags` but those don't make as much sense to move to this org, so figured I would start by asking about the parser.

**Comment by wesleytodd** [comment]
I went ahead and [did the extraction](https://github.com/wesleytodd/conventional-commits-parser), but it looks like I am missing all the release tags.  I think I should be able to also extract those but that is something I have never tried before.

**Comment by damianopetrungaro** [comment]
I'd love to add as much tooling around the spec here as well!
The only suggestion from my side would be naming it `parsers-js` so people using different languages can write a parser as well.

(I added a PHP CLI tool for example here, and started a Go one a few months ago but never finished)

**Comment by wesleytodd** [comment]
Awesome!  I agree changing the repo name would be the right thing to do when we move it into the org, to be clear though, my original goal was to make the npm package called `conventional-commits-parser` live in a repo here, so the package name would still be `conventional-commits-parser`.

**Comment by damianopetrungaro** [comment]
@wesleytodd can't you rename the library on NPM side?

**Comment by wesleytodd** [comment]
We could, but since npm is really only used for JS packages, I wonder what the point would be?  If anything I would see the repo name being `conventional-commits-parser-js` or something like that so we can host other language parser in this org, but then let each publish under the name which makes the most sense to their ecosystems.  Does that make sense?

**Comment by bcoe** [comment]
There's an effort to build a parser [here](https://github.com/conventional-commits/parser). My thinking was that we'd publish this to `@conventional-commits/parser` on npm, and `conventional-commits-parser` would be a legacy library that continues to live in the `conventional-changelog` org, but pulls in our parser.

**Comment by wesleytodd** [comment]
I am going to close this now that we have https://github.com/conventional-commits/parser
