### ISSUE TITLE
New time for meeting

### ISSUE THREAD

**Issue by bcoe** [conventional-commits/meta#8]
@wesleytodd and I would be able to meet a bit earlier, which could be better for European folks.

@wesleytodd a day other than Friday would potentially be better, (@bcoe would be open to Thursday or Wednesday, with a preference for Thursday).

@byCedric, @damianopetrungaro, @eemeli.

**Comment by damianopetrungaro** [comment]
I’d love to do that another day, with the time I’m cool since it’s end of
working day in my timezone (CEST)

**Comment by eemeli** [comment]
Wednesdays and Thursdays are definitely better for me than Fridays. I've two recurring meeting on Thursdays, 14:00-15:30 (weekly) and 17:00-19:30 (monthly) UTC, so not conflicting with those would be nice.

**Comment by wesleytodd** [comment]
I am fine with either Wed or Th if we pick a time a bit early (anything before 17:00 UTC).

**Comment by damianopetrungaro** [comment]
@bcoe do we wanna officially move it?

**Comment by bcoe** [comment]
Could I suggest `16:00 - 17:00 UTC Thursday`?

**Comment by damianopetrungaro** [comment]
Better than the current one, I'd have picked even a couple hours before but I'm cool with that 😀

**Comment by bcoe** [comment]
I've moved the meeting time to ` 16:00 - 17:00 UTC Thursday` as discussed, looking forward to next meeting with folks.
